<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: razvan
 * Date: Mon, 28 Dec 2009 11:41:30 +0200
 */

$conf['title'] = 'SO Wiki';
$conf['start'] = 'home';
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['sneaky_index'] = 1;
$conf['securecookie'] = 0;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['sepchar'] = '-';
$conf['plugin']['indexmenu']['page_index'] = 'home:index';
$conf['plugin']['indexmenu']['skip_index'] = '/(home|playground)/';
$conf['plugin']['indexmenu']['skip_file'] = '/^:home:index.txt$/';
$conf['plugin']['creole']['precedence'] = 'creole';

# LDAP authentication configuration
# $conf['authtype'] = 'ldap';
$conf['auth']['ldap']['port'] = '636';
$conf['auth']['ldap']['server'] = 'ldaps://swarm.cs.pub.ro';
$conf['auth']['ldap']['usertree'] = 'ou=People,dc=swarm,dc=cs,dc=pub,dc=ro';
$conf['auth']['ldap']['grouptree'] = 'ou=Group,dc=swarm,dc=cs,dc=pub,dc=ro';
$conf['auth']['ldap']['userfilter'] = '(&(uid=%{user})(objectClass=posixAccount))';
$conf['auth']['ldap']['groupfilter'] = '(&(objectClass=posixGroup)(|(gidNumber=%{gid})(memberUID=%{user})))';
$conf['auth']['ldap']['version'] = '3';
$conf['auth']['ldap']['mapping']['name'] = 'cn';
$conf['auth']['ldap']['mapping']['grps'] = 'array(\'memberof\' => \'/CN=(.+?),/i\')';
$conf['auth']['ldap']['debug'] = '1';

// end auto-generated content
