#!/bin/bash
# Usage:
#   ./script <destination-path> <dokuwiki-url>

# path example:
# http://www.splitbrain.org/_media/projects/dokuwiki/dokuwiki-2009-02-14.tgz

if [ $# -ne 3 ]; then
	echo "Error - Usage:"
	echo "  $0 <destination-path> <dokuwiki-latest-version-url> <visible-dokuwiki-url>"
	exit 1
fi

DEST_PATH=$1
DW_DOWN_URL=$2
DW_URL=$3

if ! [ -d $DEST_PATH ]; then
	echo "Error: first argument has to be an existing folder"
	exit 1
fi

# check if destionation folder is empty
_tmp_str=$(find $DEST_PATH -mindepth 1)
if ! test -z "$_tmp_str"; then
	echo "$DEST_PATH is not an empty folder."
	echo -n "  Continue installation? (Y/n) "
	read ans
	if test $ans = "n"; then
		exit 0
	fi
fi

# === download ===
echo "* Using download link $DW_DOWN_URL"
echo -n "  * Downloading DokuWiki ... "

cd $DEST_PATH
wget $DW_DOWN_URL -O dokuwiki.tar.gz -a wget.log
tar zxf dokuwiki.tar.gz
d=$(find . -maxdepth 1 -type d | grep -v "^.$" | head -n 1)

mv $d/* .

echo " done."

# === do basic preps ===
echo -n "* Preparing installation folder $DEST_PATH ... "

# cleanup
rm $d/.htaccess.dist
rmdir $d
rm -f dokuwiki.tar.gz

# adding write permissions to conf and data dirs
chmod -R g+w conf/
chmod -R g+w data/

# update install.php with dokuwiki.php hash
hash=$(md5sum conf/dokuwiki.php | cut -d ' ' -f 1)
date=$(date +%Y-%m-%d)
sed -ibak "s/^\(\$dokuwiki_hash.*\)$/\1\n    '$date'   => '$hash',/" install.php

echo "done."

old_dir=$(pwd)

# === install plugins === #
echo "* Installing plugins"
cd lib/plugins/

echo -n "  * Installing plugin: Creole ... "
# Plugin: Creole
# from: http://www.dokuwiki.org/plugin:creole
wget http://www.chimeric.de/_src/plugin-creole.tgz -a wget.log
tar zxf plugin-creole.tgz
rm -f plugin-creole.tgz
echo "done."

echo -n "  * Installing plugin: Google Analytics ... "
# Plugin: Google Analytics
# from: http://www.dokuwiki.org/plugin:googleanalytics
wget http://cloud.github.com/downloads/tatewake/dokuwiki-plugin-googleanalytics/googleanalytics-stable.tar.gz -a wget.log
tar -xzf googleanalytics-stable.tar.gz > /dev/null
rm -f googleanalytics-stable.tar.gz
echo "done."

echo -n "  * Installing plugin: Include ... "
# Plugin: include
# from: http://www.dokuwiki.org/plugin:include
wget http://www.chimeric.de/_src/plugin-include.tgz -a wget.log
tar -xzf plugin-include.tgz
rm -f plugin-include.tgz
echo "done."

echo -n "  * Installing plugin: Index-Menu ... "
# Plugin: index menu
# from: http://www.dokuwiki.org/plugin:indexmenu
wget http://samuele.netsons.org/dokuwiki/media/indexmenu.zip -a wget.log
unzip indexmenu.zip > /dev/null
rm -f indexmenu.zip
echo "done."

echo -n "  * Installing plugin: Display-Wiki-Page ..."
# Plugin: display wiki page
# from: http://www.dokuwiki.org/plugin:displaywikipage
wget http://cloud.github.com/downloads/tatewake/dokuwiki-plugin-displaywikipage/displaywikipage-stable.tar.gz -a wget.log
tar -xzf displaywikipage-stable.tar.gz > /dev/null
rm -f displaywikipage-stable.tar.gz
echo "done."

# add slash to DokuWiki URL in case it doesn't exist
dw_url_slash=$(sed "s|[/]\?[ \t]*/$|/|" <<<"$DW_URL/")

# extract rewrite base (for mod_rewrite) (remove http[s]://$host_name)
rw_base=$(sed "s|^http[s]\?://[^/]\+||" <<<"$dw_url_slash")

echo; echo
echo "Installation complete."
echo "1. Open in web browser: ${dw_url_slash}install.php"
echo "2. After the install procedure run:"
echo "   ./post_install_dokuwiki $DEST_PATH $rw_base"
echo
echo "Now you're done."
