#!/bin/bash

#
# Upgrade Dokuwiki installation
#
# Sample run:
#    ./upgrade_dokuwiki ~srisp/public_html/dokuwiki/ ~srisp/public_html/bak/ http://www.splitbrain.org/_media/projects/dokuwiki/dokuwiki-2009-12-25c.tgz
#
# 2010, Razvan Deaconescu, razvan@rosedu.org
#

function err()
{
	echo $* 1>&2
}

if test $# -ne 3; then
	err "Error - Usage:"
	err "  $0 <dokuwiki-install-path> <backup-path> <dokuwiki-download-url>"
	exit 1
fi

DOKUWIKI_PATH=$1
BACKUP_PATH=$2
DOKUWIKI_URL=$3
WORKING_DIR=/tmp
DOKUWIKI_TMP=dokuwiki
LOGFILE=$(mktemp)

function check()
{
	if ! test -d $DOKUWIKI_PATH; then
		err "Error: $DOKUWIKI_PATH is not a folder"
		exit 1
	fi

	if ! test -d $BACKUP_PATH; then
		err "Error: $BACKUP_PATH is not a folder"
		exit 1
	fi
}

function init()
{
	cd $WORKING_DIR
	rm -fr $DOKUWIKI_TMP
	mkdir $DOKUWIKI_TMP
	cd $DOKUWIKI_TMP

        echo "Log file is $LOGFILE."
	echo -n " * Downloading Dokuwiki from $DOKUWIKI_URL ... "
	wget "$DOKUWIKI_URL" -O $DOKUWIKI_TMP.tar.gz -a $LOGFILE
	echo "done"
	
	echo -n " * Unpacking Dokuwiki to $WORKING_DIR/$DOKUWIKI_TMP ... "
	tar xzf $DOKUWIKI_TMP.tar.gz
	rm $DOKUWIKI_TMP.tar.gz
	dname=$(find -mindepth 1 -maxdepth 1 | head -n 1)
	mv $dname/* .
	rm -fr $dname
	echo "done"
}

function backup()
{
	backup=$BACKUP_PATH/dokuwiki-bak-$(date +%Y-%m-%d)
	echo -n " * Backing up Dokuwiki instance to $backup ... "
	'cp' -fr $DOKUWIKI_PATH $backup > /dev/null 2>&1
	echo "done"
}

function upgrade()
{
	echo -n " * Upgrading Dokuwiki installation in $DOKUWIKI_PATH ... "
	'cp' -fr $WORKING_DIR/$DOKUWIKI_TMP/* $DOKUWIKI_PATH
        rm -f $DOKUWIKI_PATH/install.php
	echo "done"
}

function upgrade_plugins()
{
    pushd $DOKUWIKI_PATH/lib/plugins/ > /dev/null

    echo "* Installing plugins"

    echo -n "  * Installing plugin: Creole ... "
    # Plugin: Creole
    # from: http://www.dokuwiki.org/plugin:creole
    wget https://github.com/dokufreaks/plugin-creole/tarball/master -O plugin-creole.tar.gz -a $LOGFILE
    tar xzf plugin-creole.tar.gz > /dev/null 2>&1
    rm -fr creole
    mv *-plugin-creole-* creole
    rm -f plugin-creole.tar.gz
    echo "done."

    echo -n "  * Installing plugin: Google Analytics ... "
    # Plugin: Google Analytics
    # from: http://www.dokuwiki.org/plugin:googleanalytics
    wget http://cloud.github.com/downloads/tatewake/dokuwiki-plugin-googleanalytics/googleanalytics-stable.tar.gz -a $LOGFILE
    tar xzf googleanalytics-stable.tar.gz > /dev/null 2>&1
    rm -f googleanalytics-stable.tar.gz
    echo "done."

    echo -n "  * Installing plugin: Include ... "
    # Plugin: include
    # from: http://www.dokuwiki.org/plugin:include
    wget http://github.com/dokufreaks/plugin-include/tarball/master -O plugin-include.tar.gz -a $LOGFILE
    tar xzf plugin-include.tar.gz > /dev/null 2>&1
    # Remove old include folder. Add new one.
    rm -fr include
    mv *-plugin-include-* include
    rm -f plugin-include.tar.gz
    echo "done."

    echo -n "  * Installing plugin: Index-Menu ... "
    # Plugin: index menu
    # from: http://www.dokuwiki.org/plugin:indexmenu
    wget http://samuele.netsons.org/dokuwiki/media/indexmenu.zip -a $LOGFILE
    unzip -o indexmenu.zip > /dev/null 2>&1
    rm -f indexmenu.zip
    echo "done."

    echo -n "  * Installing plugin: Display-Wiki-Page ..."
    # Plugin: display wiki page
    # from: http://www.dokuwiki.org/plugin:displaywikipage
    wget http://cloud.github.com/downloads/tatewake/dokuwiki-plugin-displaywikipage/displaywikipage-stable.tar.gz -a $LOGFILE
    tar xzf displaywikipage-stable.tar.gz > /dev/null 2>&1
    rm -f displaywikipage-stable.tar.gz
    echo "done."

    popd > /dev/null

    pushd $DOKUWIKI_PATH > /dev/null
    echo -n "  * Installing ggauth backend ..."
    # Experimental Auth Backends
    # from: http://www.dokuwiki.org/auth:ggauth
    wget http://lastweekend.com.au/ggauth.5.zip -a $LOGFILE
    unzip -o ggauth.5.zip > /dev/null 2>&1
    rm -f ggauth.5.zip
    echo "done."
    popd > /dev/null
}

function cleanup()
{
	echo -n " * Cleaning up temporary files ... "
	rm -fr $WORKING_DIR/$DOKUWIKI_TMP.tar.gz && rm -fr $WORKING_DIR/$DOKUWIKI_TMP
	echo "done"
}

echo

cleanup
check
init
backup
upgrade
upgrade_plugins
cleanup

echo

exit 0
